### PR TITLE
Feature/node 16

### PR DESCRIPTION
**Pull request by gelks**
Support Node 13+

### CODE REVIEW

**Comment by andrisi** [comment]
Was this ever meant to run on Windows too?

**Comment by dengelke** [comment]
See issue #10, not yet resolved as I don't have a windows machine to test on

**Comment by andrisi** [comment]
Windows 10 works fine without activation for a month, on VirtualBox or QEMU.

**Comment by dengelke** [comment]
Thanks @andrisi I'll give it a look, [these VMs](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/) from Windows seem super handy

**Comment by gelks** [comment]
@andrisi #19 is now merged, please let me know how you go

**Comment by andrisi** [comment]
@gelks works like a charm!

**Comment by andrisi** [comment]
@gelks sorry to bother you, but could you point to some doc which is relevant about the query syntax and types I can use? I know it depends on Yaz. For Example I do a `f @attr 1=1 "Merle Robert"` query in yaz-client, it works fine, but gives 0 results in js. Just "Merle" gives the same number of results both places. Maybe it's they kind of quotes it expects or somethig like that?

**Comment by dengelke** [comment]
@andrisi not really 100% sure but was able to get results by running

```
zoom.connection('192.83.186.170:210/INNOPAC')
  .set('preferredRecordSyntax', 'usmarc')
  .query('prefix', `@attr 1=1 "Merle, Robert"`)
  .createReadStream()
  .on('data', (record) => {
    console.log(record.xml);
  });
```

Here are some basic docs https://software.indexdata.com/yaz/doc/tools.html#PQF

You could also try using CQL as well, which is somewhat more human readable instead of PQN/PQF as well

**Comment by dengelke** [comment]
@andrisi if you could create another issue for this one if still having issues, if you do have success would be great to have the links you found useful to provide as part of the README here

**Pull request merged**
